<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Assets\Group 12.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="HistoryPage\history.html" />
    <None Remove="HistoryPage\script.js" />
    <None Remove="HistoryPage\style.css" />
    <None Remove="Settings\data.json" />
    <None Remove="Settings\script.js" />
    <None Remove="Settings\Settings.html" />
    <None Remove="Settings\Settings.json" />
    <None Remove="Settings\style.css" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="HistoryPage\history.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HistoryPage\script.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HistoryPage\style.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Shortcut\shortcut.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.Wpf.NETCore" Version="146.0.100" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.7" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="YamlDotNet" Version="17.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Group 12.ico" />
    <Content Include="Homepage\home.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Homepage\style.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Settings\data.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Settings\script.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Settings\Settings.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Settings\Settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Settings\style.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Settings\session.yaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="chromiumembeddedframework.runtime.win-arm64" Version="146.0.10" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="chromiumembeddedframework.runtime.win-x64" Version="146.0.10" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="chromiumembeddedframework.runtime.win-x86" Version="146.0.10" />
  </ItemGroup>

</Project>
